### ISSUE TITLE
Totally wont get you hacked

### ISSUE THREAD

**Issue by Jayxens** [LillyMug/Dc-TokenGen#8]

**Comment by LillyMug** [comment]
what

**Comment by BumbleBee-2349** [comment]
this is a token logger 💀 
deobsfucate main.py and spam the webhook

**Comment by Jayxens** [comment]
> this is a token logger 💀 deobsfucate main.py and spam the webhook

how did you deobfuscate it, i tried.

**Comment by 0x3C50** [comment]
> this is a token logger skull deobsfucate main.py and spam the webhook

the webhook is already deleted

**Comment by BumbleBee-2349** [comment]
reopen this lmao the webhook got spammed so hard it’s funny 😭

Sent from my iPhone

On 23 Dec 2022, at 13:57, LillyMug ***@***.***> wrote:

﻿

Closed #8<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLillyMug%2FDc-TokenGen%2Fissues%2F8&data=05%7C01%7C%7Cfa102667ec62414d432108dae4eda147%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638074006506806219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6P0bXRprmzw3tFo2hfYv9lX%2F%2FVuk69LsH6ynQZsat8g%3D&reserved=0> as completed.
