### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Wheatlyz** [LillyMug/Dc-TokenGen#9]
****

This is a obfuscated program which means they author is trying to hide something, this most commonly happens when the intentionally add malicious code in a program, obfuscation makes it harder to read by other programmers who may just be checking that it is not malicious. 
In the discord when i called the creator out he gave no response and closed the ticket, forcing me to inform all of you. If you look at the closed issues it shows a bunch of other people who mentioned many of the same points and the creator just deleted them.

**Comment by LillyMug** [comment]
Na Bro i just have a big problem with pp that call it malware and yea i know its sus to that the programm is obfuscated but if you do somthing like this open source in one week 20 skid try to sell it and 30 other skids repost it / and sorry that i closed your ticked didn missclick or somthing

**Comment by Jayxens** [comment]
> This is a obfuscated program which means they author is trying to hide something, this most commonly happens when the intentionally add malicious code in a program, obfuscation makes it harder to read by other programmers who may just be checking that it is not malicious. In the discord when i called the creator out he gave no response and closed the ticket, forcing me to inform all of you. If you look at the closed issues it shows a bunch of other people who mentioned many of the same points and the creator just deleted them.

He also closed mine lmao

**Comment by 51L3N7-X** [comment]
grabber ..

**Comment by Leowastakenroblox** [comment]
U can clearly see at the bottom import cryptunprotecteddata LMAO 🤡

**Comment by Wheatlyz** [comment]
@LillyMug I understand working hard to make a program and not wanting people to steal it. I understand not wanting people to call it a rat or malware. Github was a meant to be a place for sharing *open source* software. If you don't want people to steal your code you should've posted it somewhere else. If it wasn't malware I think you should've been able to prove to us that it wasn't by de obfuscating it. Your approach by modifying everyone's comments and deleting the ones that called it out is unusual. I am willing to give you 72 hours to post to the de obfuscated code or I can report this to github and have your code taken down as well as your discord server.

**Comment by Salomao31** [comment]
I am in gihub :D

**Comment by Salomao31** [comment]
Its virus tho

**Comment by Kubzelll** [comment]
If this isn't malicous why its detected as malware.  I am 100% sure you will delete this comment. Also github is for open source not for obfuscated scripts. Don't run this

**Comment by ayaanok** [comment]
Coz it's fake its uses random, decoded version: 
import random
import string
import time

def generate_token(length):
  return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def main():
  length = int(input('Enter token length: '))
  token = generate_token(length)
  print(token)

main()
time.sleep(10)

**Comment by Kubzelll** [comment]
Also in this obfuscated file there is some sus imports ```import os, platform, re, threading, uuid, requests, wmi, subprocess, sqlite3, psutil, json, base64;from tkinter import messagebox;from shutil import copy2;from zipfile import ZipFile;from Crypto.Cipher import AES;from discord import Embed, File, SyncWebhook;from PIL import ImageGrab;from win32crypt import CryptUnprotectData``` Syncwebhook AES it looks like its for stealing data and sent it through discord webhook

**Comment by zEncrypte** [comment]
It's obfuscation with hyperion, usually used to obfuscate malware but don't worry in a few minutes I'll finish obfuscating it :D

**Comment by Kubzelll** [comment]
Can you send deobfuscated this here?

**Comment by zEncrypte** [comment]
yep

**Comment by Kubzelll** [comment]
I reported this to github I hope they will delete this
